### PR TITLE
Dev config upgrade

### LINKED ISSUE #206: refgenconf version
`refgenie --version` could also display the refgenconf version, that would be nice.

### PR DESCRIPTION
**Pull request by xuebingjie1990**
add cmd for `refgenie upgrade`. show `refgenconf` version with `refegenie --version`
resolve #206 #203

### CODE REVIEW

**Comment by nsheff** [comment]
There were 3 things we were waiting on for this release to dev:
- make alias links relative
- finalize upgrade function (@xuebingjie1990)
- test

**Comment by nsheff** [comment]
Hi @stolarczyk the upgrade tutorial is great! Should we also update the example here? http://refgenie.databio.org/en/latest/genome_config/

**Comment by stolarczyk** [comment]
yes, we definitely need to update the config example. I'll go through all the docs before this release, there are probably other spots that need updates.

**Comment by stolarczyk** [comment]
and to add to your todo list -- we need to build and archive assets and deploy the new refgenieserver software

**Comment by stolarczyk** [comment]
> the upgrade tutorial is great!

There's also a [jupyter notebook](https://github.com/refgenie/refgenie/blob/dev_config_upgrade/docs_jupyter/config_upgrade_03_to_04.ipynb) that demonstrates that. We'll need to run this again since 
 there were some changes made to the upgrade feature since I wrote it.

**Comment by nsheff** [comment]
> There's also a jupyter notebook that demonstrates that.

ah -- that wasn't linked into the docs so I didn't find it. I'll add a link

**Comment by nsheff** [comment]
With this I think I'd suggest combining the two non-jupyter docs on the config file into one -- in other words, adding the upgrade info to the main genome config reference page. any objections?

**Comment by stolarczyk** [comment]
no, I'm ok with that

**Comment by nsheff** [comment]
Ok I merged those, and changed it to a "Changelog" format, which to me separated things out better, so take a look when you have a chance.

**Comment by nsheff** [comment]
Ok looks like this is ready, just need to test it, I guess. So, should we update the lab stuff and have everyone move over to the new system?

**Comment by stolarczyk** [comment]
I think so. 

1. I'll give the refgenieserver, refgenconf and this PR one last look today and update the docs
2. then we can upgrade the lab config
3. if everything goes well we can trigger asset building/archiving jobs and deploy the server
4. once the server is up and running we make the releases? This means we need to deploy a refgenieserver instance using the dev refgenconf.

**Review by stolarczyk — APPROVED** [review]

**Pull request merged**
