### PR TITLE
add bed12 build recipe

### PR DESCRIPTION
**Pull request by mirpedrol**

### CODE REVIEW

**Comment by stolarczyk** [comment]
The new recipe looks good, but it follows a recipe specification that is about to change. I'm not sure what is the timeline for the release (@nsheff?) 

However, this is intended to be used in conjunction with https://github.com/refgenie/aws_igenomes/pull/1, so you'll need to change the base branch to `dev`. We added asset classes concept in the development version of Refgenie and enhanced the recipes format and handling. Check these links out for some context:
- [asset class specification](http://refgenie.databio.org/en/dev/asset_class_specification/)
- [recipe specification](http://refgenie.databio.org/en/dev/recipe_specification/)

**Comment by asthara10** [comment]
Hi @stolarczyk, thank you for your feedback! 
Would it be better to create a PR to [refgenie/recipes](https://github.com/refgenie/recipes) then? Following the new recipe format and creating also an asset class?

**Comment by stolarczyk** [comment]
That's right. So PRs to this repo are not required to add new recipes after all.

**Comment by mirpedrol** [comment]
Closing this as the bed12 will be added [here](https://github.com/refgenie/recipes/pull/1) according to the new recipes strategy.

**Pull request closed without merging**
